version: "2"
services:
  api:
    build: .
    volumes:
      - ./src:/usr/app
    ports:
      - 3000:3001
    environment:
      - ENV=dev
      - PORT=3001
    entrypoint: |
      bash -c 'bash -s <<EOF
        yarn install && npm run serve:dev
      EOF'
  db:
    image: mariadb
    ports:
      - 3307:3306
    environment:
      - MYSQL_DATABASE=idonis
      - MYSQL_USER=user
      - MYSQL_PASSWORD=123
      - MYSQL_ROOT_PASSWORD=root
